/**
 * AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Generated by: scripts/generate-nuevos-r2-catalog.mjs
 * Generated at: 2026-03-04T16:21:31.902Z
 * UTC day bucket at generation: 20516
 *
 * Source manifest: public/uploads/videos/does-not-exist.csv
 * Note: source manifest was not found during generation.
 */

import type { ReelClip } from '@/data/portfolio-clips';

export const NUEVOS_R2_READY_CLIPS: ReelClip[] = [

];

export const NUEVOS_R2_BLOCK_REPORT: {
  totalCandidates: number;
  ready: number;
  blocked: number;
  missingByAsset: {
    main: number;
    mobile: number;
    preview: number;
    poster: number;
  };
} = {
  totalCandidates: 0,
  ready: 0,
  blocked: 0,
  missingByAsset: {
    main: 0,
    mobile: 0,
    preview: 0,
    poster: 0,
  },
};
