
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next'; // Import useTranslation
import { Menu, X } from 'lucide-react';

const Navbar = () => {
  const { t, i18n } = useTranslation(); // Initialize useTranslation and get i18n instance
  const [isScrolled, setIsScrolled] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 20);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  // Define keys and hrefs, name will be generated by t()
  const navLinkKeys = [
    { key: 'navbar.home', href: '#home' },
    { key: 'navbar.services', href: '#services' },
    { key: 'navbar.portfolio', href: '#portfolio' },
    { key: 'navbar.testimonials', href: '#testimonials' },
    { key: 'navbar.contact', href: '#contact' },
  ];

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
  };

  return (
    <nav 
      className={`fixed top-0 left-0 w-full z-50 transition-all duration-300 ${
        isScrolled 
          ? 'py-3 glass shadow-sm' 
          : 'py-5 bg-transparent'
      }`}
    >
      <div className="container mx-auto px-6 md:px-12">
        <div className="flex items-center justify-between">
          <a 
            href="#home" 
            className="text-xl md:text-2xl font-medium font-cormorant text-primary italic"
          >
            Gisela<span className="text-foreground not-italic font-normal">.UGC</span>
          </a>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-8">
            {navLinkKeys.map((link) => (
              <a
                key={link.key} // Use key for React key
                href={link.href}
                className="text-sm text-foreground hover-lift hover:text-primary/80 transition-all"
              >
                {t(link.key)} {/* Use t() for translation */}
              </a>
            ))}
            {/* Language Switcher - Desktop */}
            <div className="flex items-center space-x-2 ml-4 border-l border-border/30 pl-4">
              <button
                onClick={() => changeLanguage('es')}
                className={`text-sm font-medium ${i18n.resolvedLanguage === 'es' ? 'text-primary font-semibold' : 'text-foreground/70 hover:text-foreground'}`}
                aria-label={t('languageSwitcher.changeLanguage') + ' a Español'}
              >
                ES
              </button>
              <span className="text-foreground/30 text-sm">|</span>
              <button
                onClick={() => changeLanguage('en')}
                className={`text-sm font-medium ${i18n.resolvedLanguage === 'en' ? 'text-primary font-semibold' : 'text-foreground/70 hover:text-foreground'}`}
                 aria-label={t('languageSwitcher.changeLanguage') + ' to English'}
             >
                EN
              </button>
            </div>
            <a
              href="#contact"
              className="px-6 py-2.5 rounded-full bg-primary text-white text-sm hover-grow shadow-sm ml-4" // Added margin
            >
              {t('navbar.hireMe')} {/* Use t() for translation */}
            </a>
          </div>

          {/* Mobile Navigation Toggle */}
          {/* Mobile Navigation - Right Side (Switcher & Toggle) */}
          <div className="md:hidden flex items-center space-x-4">
            {/* Language Switcher - Mobile Header */}
            <div className="flex items-center space-x-2">
              <button
                onClick={() => changeLanguage('es')}
                className={`text-sm font-medium ${i18n.resolvedLanguage === 'es' ? 'text-primary font-semibold' : 'text-foreground/70 hover:text-foreground'}`}
                aria-label={t('languageSwitcher.changeLanguage') + ' a Español'}
              >
                ES
              </button>
              <span className="text-foreground/30 text-sm">|</span>
              <button
                onClick={() => changeLanguage('en')}
                className={`text-sm font-medium ${i18n.resolvedLanguage === 'en' ? 'text-primary font-semibold' : 'text-foreground/70 hover:text-foreground'}`}
                 aria-label={t('languageSwitcher.changeLanguage') + ' to English'}
             >
                EN
              </button>
            </div>
            {/* Mobile Menu Toggle */}
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="text-foreground hover:text-primary transition-colors"
              aria-label={mobileMenuOpen ? t('navbar.closeMenu') : t('navbar.openMenu')}
            >
              {mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Navigation Menu */}
      <div 
        className={`fixed inset-x-0 top-[61px] glass md:hidden p-6 transition-all duration-300 ease-in-out ${
          mobileMenuOpen ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-10 pointer-events-none'
        }`}
      >
        <div className="flex flex-col space-y-4">
          {navLinkKeys.map((link) => (
            <a
              key={link.key} // Use key for React key
              href={link.href}
              className="text-foreground py-2 hover:text-primary transition-all border-b border-border/30"
              onClick={() => setMobileMenuOpen(false)}
            >
              {t(link.key)} {/* Use t() for translation */}
            </a>
          ))}
          <a
            href="#contact"
            className="px-6 py-2.5 text-center rounded-full bg-primary text-white hover-grow mt-2"
            onClick={() => setMobileMenuOpen(false)}
          >
            {t('navbar.hireMe')} {/* Use t() for translation */}
          </a>
          {/* Language Switcher removed from here */}
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
