
import { useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { Play, Maximize, X } from 'lucide-react';

// Define an interface for the portfolio item structure
interface PortfolioItem {
  id: number;
  titleKey: string;
  category: 'fashion' | 'beauty' | 'tech' | 'lifestyle'; // Use specific categories
  thumbnail: string;
  type: 'image' | 'video';
}

const Portfolio = () => {
  const { t } = useTranslation(); // Initialize useTranslation
  const [activeFilter, setActiveFilter] = useState('all');
  // Use the interface for the state type, allowing null initially
  const [selectedItem, setSelectedItem] = useState<PortfolioItem | null>(null);

  // Define category keys, name will be generated by t()
  const categoryKeys = [
    { id: 'all', nameKey: 'portfolio.categories.all' },
    { id: 'fashion', nameKey: 'portfolio.categories.fashion' },
    { id: 'beauty', nameKey: 'portfolio.categories.beauty' },
    { id: 'tech', nameKey: 'portfolio.categories.tech' },
    { id: 'lifestyle', nameKey: 'portfolio.categories.lifestyle' }
  ];

  // Store keys, icons, etc., text will come from t()
  // Explicitly type the array with the interface
  const portfolioItemData: PortfolioItem[] = [
    {
      id: 1,
      titleKey: 'portfolio.items.item1',
      category: 'fashion', // Keep category id for filtering
      thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'image'
    },
    {
      id: 2,
      titleKey: 'portfolio.items.item2',
      category: 'beauty',
      thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'video'
    },
    {
      id: 3,
      titleKey: 'portfolio.items.item3',
      category: 'tech',
      thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'image'
    },
    {
      id: 4,
      titleKey: 'portfolio.items.item4',
      category: 'lifestyle',
      thumbnail: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'image'
    },
    {
      id: 5,
      titleKey: 'portfolio.items.item5',
      category: 'beauty',
      thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'video'
    },
    {
      id: 6,
      titleKey: 'portfolio.items.item6',
      category: 'fashion',
      thumbnail: 'https://images.unsplash.com/photo-1520999166575-37d109989923?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'image'
    },
    {
      id: 7,
      titleKey: 'portfolio.items.item7',
      category: 'tech',
      thumbnail: 'https://images.unsplash.com/photo-1551721434-8b94ddff0e6d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'video'
    },
    {
      id: 8,
      titleKey: 'portfolio.items.item8',
      category: 'lifestyle',
      thumbnail: 'https://images.unsplash.com/photo-1498575732665-aac7705c2c7d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      type: 'video'
    }
  ];

  const filteredItems = activeFilter === 'all'
    ? portfolioItemData
    : portfolioItemData.filter(item => item.category === activeFilter);

  const closeModal = () => {
    setSelectedItem(null);
  };

  return (
    <section id="portfolio" className="section-padding relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-background via-brand-cream/60 to-secondary/45" />
      <div className="absolute left-[-14rem] bottom-[-10rem] h-[24rem] w-[24rem] rounded-full bg-primary/10 blur-[120px]" />
      <div className="container relative z-10 mx-auto">
        <div className="text-center mb-16">
          <p className="text-brand-olive mb-3 uppercase tracking-[0.18em] font-semibold">{t('portfolio.sectionSubtitle')}</p>
          <h2 className="text-3xl md:text-4xl font-bold font-playfair mb-6">{t('portfolio.sectionTitle')}</h2>
          <div className="w-24 h-1 signature-line mx-auto" />
        </div>

        <div className="flex flex-wrap justify-center gap-4 mb-10">
          {categoryKeys.map((category) => (
            <button
              key={category.id}
              onClick={() => setActiveFilter(category.id)}
              className={`px-6 py-2 rounded-full text-sm transition-all ${activeFilter === category.id
                  ? 'bg-gradient-to-r from-primary to-brand-teal text-primary-foreground shadow-md'
                  : 'cafe-chip hover:bg-secondary'
                }`}
            >
              {t(category.nameKey)} {/* Use t() for category name */}
            </button>
          ))}
        </div>

        <div className="columns-1 md:columns-2 lg:columns-4 gap-6 space-y-6">
          {filteredItems.map((item, index) => {
            // 3D tilt effect handler
            const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
              const el = e.currentTarget;
              const rect = el.getBoundingClientRect();
              const x = (e.clientX - rect.left - rect.width / 2) / 15;
              const y = (e.clientY - rect.top - rect.height / 2) / 15;
              el.style.transform = `perspective(1000px) rotateY(${x}deg) rotateX(${-y}deg) scale(1.02)`;
            };
            const handleMouseLeave = (e: React.MouseEvent<HTMLDivElement>) => {
              e.currentTarget.style.transform = 'perspective(1000px) rotateY(0) rotateX(0) scale(1)';
            };

            // Variable aspect ratios for masonry effect
            const aspectRatios = ['4/3', '1/1', '3/4', '16/9'];
            const aspect = aspectRatios[index % aspectRatios.length];

            return (
              <div
                key={item.id}
                className="group relative overflow-hidden rounded-2xl border border-primary/15 shadow-sm cursor-pointer break-inside-avoid mb-6 transition-all duration-300 ease-out bg-card/75"
                onClick={() => setSelectedItem(item)}
                onMouseMove={handleMouseMove}
                onMouseLeave={handleMouseLeave}
                style={{ transformStyle: 'preserve-3d' }}
              >
                <div className="w-full overflow-hidden" style={{ aspectRatio: aspect }}>
                  <img
                    src={item.thumbnail}
                    alt={t(item.titleKey)}
                    className="w-full h-full object-cover"
                    loading="lazy"
                    decoding="async"
                  />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-brand-cocoa/85 via-brand-cocoa/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-5">
                  <h3 className="text-brand-cream font-medium mb-1">{t(item.titleKey)}</h3>
                  <p className="text-brand-cream/75 text-sm capitalize">{t(`portfolio.categories.${item.category}`)}</p>

                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                    {item.type === 'video' ? (
                      <div className="w-14 h-14 bg-brand-cream/90 rounded-full flex items-center justify-center">
                        <Play className="h-6 w-6 text-brand-teal fill-brand-teal" />
                      </div>
                    ) : (
                      <div className="w-14 h-14 bg-brand-cream/90 rounded-full flex items-center justify-center">
                        <Maximize className="h-6 w-6 text-brand-teal" />
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Modal */}
      {selectedItem && (
        <div
          className="fixed inset-0 z-50 bg-brand-cocoa/85 backdrop-blur-sm flex items-center justify-center p-4"
          onClick={closeModal}
        >
          <div
            className="relative max-w-4xl w-full bg-card rounded-2xl overflow-hidden animate-scale border border-primary/20"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="aspect-w-16 aspect-h-9 w-full bg-brand-cocoa">
              <img
                src={selectedItem.thumbnail}
                alt={t(selectedItem.titleKey)}
                className="w-full h-full object-cover"
              />
            </div>
            <div className="p-6">
              <h3 className="text-2xl font-cormorant text-primary">{t(selectedItem.titleKey)}</h3> {/* Use t() for title */}
              <p className="text-muted-foreground capitalize">{t(`portfolio.categories.${selectedItem.category}`)}</p> {/* Use t() for category name */}
            </div>
            <button
              className="absolute top-4 right-4 w-10 h-10 bg-brand-cream/90 rounded-full flex items-center justify-center hover:bg-brand-cream"
              onClick={closeModal}
            >
              <X className="h-5 w-5 text-brand-teal" />
            </button>
          </div>
        </div>
      )}
    </section>
  );
};

export default Portfolio;
