/**
 * AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Generated by: scripts/generate-nuevos-r2-catalog.mjs
 * Generated at: 2026-03-04T16:16:24.868Z
 * UTC day bucket at generation: 20516
 *
 * Source manifest: public/uploads/videos/nuevos/manifest.csv
 */

import type { ReelClip } from '@/data/portfolio-clips';

export const NUEVOS_R2_READY_CLIPS: ReelClip[] = [
  {
    id: 1001,
    title: 'Adds marketing',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Adds%20marketing.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Adds%20marketing-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Adds%20marketing-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Adds%20marketing-poster.jpg',
  },
  {
    id: 1002,
    title: 'Contenido Tik Tok',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Contenido%20Tik%20Tok.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Contenido%20Tik%20Tok-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Contenido%20Tik%20Tok-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Contenido%20Tik%20Tok-poster.jpg',
  },
  {
    id: 1003,
    title: 'Croma Key',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Croma%20Key.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Croma%20Key-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Croma%20Key-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Croma%20Key-poster.jpg',
  },
  {
    id: 1004,
    title: 'Croma key plano cerrado',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Croma%20key%20plano%20cerrado.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Croma%20key%20plano%20cerrado-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Croma%20key%20plano%20cerrado-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Croma%20key%20plano%20cerrado-poster.jpg',
  },
  {
    id: 1005,
    title: 'Croma key sobrepuesto',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Croma%20key%20sobrepuesto.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Croma%20key%20sobrepuesto-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Croma%20key%20sobrepuesto-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Croma%20key%20sobrepuesto-poster.jpg',
  },
  {
    id: 1006,
    title: 'DEEDCEA0 6288 4AB4 B5E5 39F8A50822E7',
    category: 'lifestyle',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/DEEDCEA0-6288-4AB4-B5E5-39F8A50822E7.MOV',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/DEEDCEA0-6288-4AB4-B5E5-39F8A50822E7-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/DEEDCEA0-6288-4AB4-B5E5-39F8A50822E7-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/DEEDCEA0-6288-4AB4-B5E5-39F8A50822E7-poster.jpg',
  },
  {
    id: 1007,
    title: 'Detrás de cámaras',
    category: 'lifestyle',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Detra%CC%81s%20de%20ca%CC%81maras.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Detra%CC%81s%20de%20ca%CC%81maras-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Detra%CC%81s%20de%20ca%CC%81maras-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Detra%CC%81s%20de%20ca%CC%81maras-poster.jpg',
  },
  {
    id: 1008,
    title: 'IMG 5793',
    category: 'lifestyle',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/IMG_5793.MOV',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/IMG_5793-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/IMG_5793-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/IMG_5793-poster.jpg',
  },
  {
    id: 1009,
    title: 'IMG 8435',
    category: 'lifestyle',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/IMG_8435.MOV',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/IMG_8435-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/IMG_8435-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/IMG_8435-poster.jpg',
  },
  {
    id: 1010,
    title: 'Reporte noticioso USA',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/Reporte%20noticioso%20USA.MP4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/Reporte%20noticioso%20USA-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/Reporte%20noticioso%20USA-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/Reporte%20noticioso%20USA-poster.jpg',
  },
  {
    id: 1011,
    title: 'WhatsApp Video 2026 02 13 at 00.02.34',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/WhatsApp%20Video%202026-02-13%20at%2000.02.34.mp4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/WhatsApp%20Video%202026-02-13%20at%2000.02.34-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/WhatsApp%20Video%202026-02-13%20at%2000.02.34-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/WhatsApp%20Video%202026-02-13%20at%2000.02.34-poster.jpg',
  },
  {
    id: 1012,
    title: 'WhatsApp Video 2026 02 13 at 00.39.53',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/WhatsApp%20Video%202026-02-13%20at%2000.39.53.mp4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/WhatsApp%20Video%202026-02-13%20at%2000.39.53-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/WhatsApp%20Video%202026-02-13%20at%2000.39.53-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/WhatsApp%20Video%202026-02-13%20at%2000.39.53-poster.jpg',
  },
  {
    id: 1013,
    title: 'WhatsApp Video 2026 02 13 at 00.42.58',
    category: 'tech',
    mainSrc: 'https://media.giselasaldarriaga.com/videos/main/WhatsApp%20Video%202026-02-13%20at%2000.42.58.mp4',
    mobileSrc: 'https://media.giselasaldarriaga.com/videos/mobile/WhatsApp%20Video%202026-02-13%20at%2000.42.58-mobile.mp4',
    previewSrc: 'https://media.giselasaldarriaga.com/videos/previews/WhatsApp%20Video%202026-02-13%20at%2000.42.58-preview.mp4',
    posterSrc: 'https://media.giselasaldarriaga.com/videos/posters/WhatsApp%20Video%202026-02-13%20at%2000.42.58-poster.jpg',
  },
];

export const NUEVOS_R2_BLOCK_REPORT: {
  totalCandidates: number;
  ready: number;
  blocked: number;
  missingByAsset: {
    main: number;
    mobile: number;
    preview: number;
    poster: number;
  };
} = {
  totalCandidates: 16,
  ready: 13,
  blocked: 3,
  missingByAsset: {
    main: 3,
    mobile: 0,
    preview: 0,
    poster: 0,
  },
};
